config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/features',    to: 'static_pages#features'
  get    '/about',       to: 'static_pages#about'
  get    '/contact',     to: 'static_pages#contact'
  get    '/signup',      to: 'users#new'
  post   '/signup',      to: 'users#create'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  resources :users do
    get '/today',        to: 'items#today',       as: 'items_today'
    get '/hamper',       to: 'items#hamper',     as: 'items_hamper'
    resources :drawers, only: :show do
      patch '/dirty',    to: 'drawers#all_clean', as: 'clean'
      resources :items, only: [:create, :update, :destroy]
    end
  end
end

app/models/drawer.rb
class Drawer < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  validates :user, presence: true
  validates :user_id, presence: true
  validates :clothing, presence: true, length: { maximum: 50 }
end

app/controllers/drawers_controller.rb
class DrawersController < ApplicationController
  before_action :logged_in_user
  before_action :set_correct_user

  # shows a drawer (one for now, more to come in version 1.1)
  def show
    @drawer = @user.drawers.find(params[:id])
    @items = @drawer.items
  end

  # changes the :dirty column value in all items in a drawer from true to false
  def all_clean
    @drawer = @user.drawers.find(params[:drawer_id])
    @drawer.items.reverse_each do |item|
      item.update_attribute(:dirty, false)
    end
    redirect_to user_items_hamper_path
    flash[:success] = 'Items returned to drawer'
  end
end

app/helpers/drawers_helper.rb
module DrawersHelper
  # finds the drawer associated with the current user
  # will be invalid when multiple drawer functionality is added
  def current_drawer
    @current_drawer ||= Drawer.find_by(user_id: session[:user_id])
  end
end

app/views/drawers/_drawer.html.erb
<li id="drawer-<%= drawer.id %>">
  <span class="clothing"><%= drawer.clothing %></span>
  <!--add link here to individual closet page when created-->
</li>

app/views/drawers/show.html.erb
<% provide(:title, "My Drawer") %>

<h1> My Drawer </h1>

<%= form_with scope: :item, url: user_drawer_items_path(@user, @drawer),
  local: true do |form| %>
  <div class="form-group">
    <%= form.label :add_a_new_clothing_item %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="contents-centered">
    <%= form.submit 'Add Item to Drawer',
    class: 'btn btn-primary col-md-2 col-sm-3' %>
  </div>
<% end %>

<hr>

<ul class="list-group">
<% @items.each do |item| %>
  <% if item.dirty == false %>
    <div class="row">
      <p>
        <li class="list-group-item col-md-6 col-sm-6"><%= item.title %></li>

        <%= link_to "Delete", [@user, @drawer, item], method: :delete,
        class: "btn btn-danger col-md-1 col-sm-2 pull-right"%>
      </p>
    </div>
  <% end %>
<% end %>