config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/features',    to: 'static_pages#features'
  get    '/about',       to: 'static_pages#about'
  get    '/contact',     to: 'static_pages#contact'
  get    '/signup',      to: 'users#new'
  post   '/signup',      to: 'users#create'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  resources :users do
    get '/today',        to: 'items#today',       as: 'items_today'
    get '/hamper',       to: 'items#hamper',     as: 'items_hamper'
    resources :drawers, only: :show do
      patch '/dirty',    to: 'drawers#all_clean', as: 'clean'
      resources :items, only: [:create, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :drawers, dependent: :destroy
  has_many :items, through: :drawers

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index]

  # displays a list of all users
  def index
    @users = User.paginate(page: params[:page])
  end

  # displays a particular user
  def show
    @user = User.find(params[:id])
  end

  # displays a signup page
  def new
    @user = User.new
  end

  # creates a User
  def create
    @user = User.new(user_params)

    if @user.save
      # this is named 'My Drawer bc at some point adding drawers will be an
      # option, in which case you could have a drawer for 'shirts', 'pants', etc
      @user.drawers.create!(clothing: 'My Drawer')
      log_in @user
      flash[:success] = 'Welcome to the Closet Ordering App'
      redirect_to user_items_today_path(@user)
    else
      render 'new'
    end
  end

  # displays a form to edit login credentials
  def edit; end

  # updates login credentials
  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  # destroys a User
  def destroy
    @user = User.find(params[:id])
    if current_user?(@user) || current_user.admin?
      User.find(params[:id]).destroy
      flash[:success] = 'User deleted'
      current_user.admin? ? (redirect_to users_url) : (redirect_to root_url)
    else
      redirect_to root_url
    end
  end

  private

    # Retrieves signup credentials from params hash
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    # Confirms the correct user with params value of :id
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, user_path(@user)) %>

<h1>Update your credentials</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>

    <div id="delete-account">
      <%= link_to "delete your account", user_path, method: :delete,
                                  data: { confirm: "You sure?" } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>