config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/features',    to: 'static_pages#features'
  get    '/about',       to: 'static_pages#about'
  get    '/contact',     to: 'static_pages#contact'
  get    '/signup',      to: 'users#new'
  post   '/signup',      to: 'users#create'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  resources :users do
    get '/today',        to: 'items#today',       as: 'items_today'
    get '/hamper',       to: 'items#hamper',     as: 'items_hamper'
    resources :drawers, only: :show do
      patch '/dirty',    to: 'drawers#all_clean', as: 'clean'
      resources :items, only: [:create, :update, :destroy]
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :drawer
  default_scope -> { order(updated_at: :desc) }
  validates :drawer, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :drawer_id, presence: true
  validates :dirty, inclusion: { in: [true, false] }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user
  before_action :set_correct_user
  before_action :set_drawer, except: [:today, :hamper]
  before_action :set_all_drawers, only: [:today, :hamper]
  before_action :set_all_items, only: [:today, :hamper]

  # creates an item
  def create
    @item = @drawer.items.new(item_title_param)

    if @item.save
      redirect_to user_drawer_path(@user, @drawer)
      flash[:success] = 'Item Added to My Drawer'
    else
      render 'drawers/show'
    end
  end

  # shows a list of all clean items
  def today; end

  # shows a list of all dirty items
  def hamper; end

  # changes the :dirty attribute from false to true for an item
  def update
    @item = @drawer.items.find(params[:id])
    @item.update_attributes(item_dirty_param)
    if @item.dirty
      flash[:success] = 'Item moved to hamper'
      redirect_to user_items_today_path(@user)
    else
      flash[:success] = 'Item returned to drawer'
      redirect_to user_items_hamper_path
    end
  end

  # destroys an Item
  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = 'Item deleted'
    redirect_to user_drawer_path(@user, @drawer)
  end

  private

    # retrieves :title value from params
    def item_title_param
      params.require(:item).permit(:title)
    end

    # retrieves :dirty value from params
    def item_dirty_param
      params.require(:item).permit(:dirty)
    end

    # finds a drawer from params
    def set_drawer
      @drawer = @user.drawers.find(params[:drawer_id])
    end

    # finds all drawers of a user
    def set_all_drawers
      @drawers = @user.drawers
    end

    # finds all items of a user
    def set_all_items
      @items = @user.items
    end
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/hamper.html.erb
<% provide(:title, "My Hamper") %>

<h1> My Dirty Clothes Hamper </h1>

<% @drawers.each do |drawer| %>
  <div class="row">
  <%= button_to "Finished Laundry", user_drawer_clean_path(@user, drawer),
    method: :patch, class: "btn btn-success col-md-3 col-sm-3 pull-right" %>
  </div>

  <ul class="list-group">
  <% @items.each do |item| %>
    <% if item.dirty == true %>
      <div class="row">
        <p>
          <li class="list-group-item col-md-6 col-sm-6"><%= item.title %></li>

        <%= button_to "Mark as Clean", [@user, drawer, item], method: :patch,
        class: "btn btn-primary col-md-2 col-sm-3 pull-right",
        params: { item: { dirty: false } } %>
        </p>
      </div>
    <% end %>
  <% end %>
  </ul>
<% end %>

app/views/items/today.html.erb
<% provide(:title, "Today") %>

<h1> My Clean Clothes </h1>

<% @drawers.each do |drawer| %>
  <ul class="list-group">
  <% @items.each do |item| %>
    <% if item.dirty == false %>
      <div class="row">
        <p>
          <li class="list-group-item col-md-6 col-sm-6"><%= item.title %></li>

          <%= button_to "Mark as Worn", [@user, drawer, item], method: :patch,
          class: "btn btn-warning col-md-2 col-sm-3 pull-right",
        params: { item: { dirty: true } } %>

        </p>
      </div>
    <% end %>
  <% end %>
<% end %>