config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/features',    to: 'static_pages#features'
  get    '/about',       to: 'static_pages#about'
  get    '/contact',     to: 'static_pages#contact'
  get    '/signup',      to: 'users#new'
  post   '/signup',      to: 'users#create'
  get    '/login',       to: 'sessions#new'
  post   '/login',       to: 'sessions#create'
  delete '/logout',      to: 'sessions#destroy'

  resources :users do
    get '/today',        to: 'items#today',       as: 'items_today'
    get '/hamper',       to: 'items#hamper',     as: 'items_hamper'
    resources :drawers, only: :show do
      patch '/dirty',    to: 'drawers#all_clean', as: 'clean'
      resources :items, only: [:create, :update, :destroy]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dresser App", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? && current_user.admin? %>
          <li>
            <%= link_to "Today", user_items_today_path(current_user) %>
          </li>
          <li>
            <%= link_to "My Drawer",
            user_drawer_path(current_user, current_drawer) %>
          </li>
          <li>
            <%= link_to "My Hamper",
            user_items_hamper_path(current_user) %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Upcoming Features", features_path %>
              </li>
              <li>
                <%= link_to "Users", users_path %>
              </li>
              <li>
                <%= link_to "Account Info", edit_user_path(current_user) %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% elsif logged_in? && !current_user.admin? %>
          <li>
            <%= link_to "Today", user_items_today_path(current_user) %>
          </li>
          <li>
            <%= link_to "My Drawer",
            user_drawer_path(current_user, current_drawer) %>
          </li>
          <li>
            <%= link_to "My Hamper",
            user_items_hamper_path(current_user) %>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Upcoming Features", features_path %>
              </li>
              <li>
                <%= link_to "Account Info", edit_user_path(current_user) %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% elsif !logged_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body id="background">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>